### ISSUE TITLE
benutzerhandbuch hinzufugen

### ISSUE THREAD

**Issue by doodzik** [htw-ai/Prog_2_beleg_1#2]
Wir sollen noch ein benutzer handbuch schreiben.

in dem  sollen wir die implemenation erklaren, testbeispiele darlegen und erklaren wie das programm anzuwenden ist.

**Comment by ch-sc** [comment]
Ja das handbuch muss ich noch machen, wo stehen dazu eigentlich die genauen anforderungen? Gibts da vllt ne folie?

-----Original Message-----

**Comment by doodzik** [comment]
ich weiss es nicht. Ich wollte meins heute oder morgen fertig schreiben. Dann kannst du dir das angucken
